# Generated by Django 5.2 on 2026-08-02 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmpresaConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_fantasia', models.CharField(default='Loca360', max_length=120)),
                ('razao_social', models.CharField(default='Locadora Alpha LTDA', max_length=160)),
                ('documento', models.CharField(default='00.000.000/0001-00', max_length=30)),
                ('email', models.EmailField(default='contato@loca360.local', max_length=254)),
                ('telefone', models.CharField(blank=True, max_length=30)),
                ('whatsapp', models.CharField(blank=True, max_length=30)),
                ('endereco', models.CharField(blank=True, max_length=220)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'configuracao da empresa',
                'verbose_name_plural': 'configuracoes da empresa',
            },
        ),
    ]
