# Generated by Django 5.2 on 2026-07-01 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ativos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rastreador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(max_length=80, unique=True)),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('sem_comunicacao', 'Sem comunicacao'), ('manutencao', 'Manutencao')], default='online', max_length=20)),
                ('bateria_percentual', models.PositiveSmallIntegerField(default=100)),
                ('sinal_gsm_percentual', models.PositiveSmallIntegerField(default=100)),
                ('usando_dados_simulados', models.BooleanField(default=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ativo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rastreador', to='ativos.ativo')),
            ],
            options={
                'verbose_name': 'rastreador',
                'verbose_name_plural': 'rastreadores',
                'ordering': ['ativo__codigo'],
            },
        ),
        migrations.CreateModel(
            name='PosicaoRastreamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('endereco_referencia', models.CharField(blank=True, max_length=180)),
                ('velocidade_kmh', models.DecimalField(decimal_places=1, default=0, max_digits=6)),
                ('registrada_em', models.DateTimeField()),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('rastreador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posicoes', to='rastreamento.rastreador')),
            ],
            options={
                'verbose_name': 'posicao de rastreamento',
                'verbose_name_plural': 'posicoes de rastreamento',
                'ordering': ['-registrada_em'],
            },
        ),
    ]
