# Generated by Django 5.2 on 2026-07-01 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ativos', '0001_initial'),
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Locacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('status', models.CharField(choices=[('orcamento', 'Orcamento'), ('agendada', 'Agendada'), ('ativa', 'Ativa'), ('finalizada', 'Finalizada'), ('cancelada', 'Cancelada')], default='orcamento', max_length=20)),
                ('valor_equipamentos', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('valor_servicos', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('valor_desconto', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='locacoes', to='clientes.cliente')),
                ('endereco_entrega', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='locacoes_entrega', to='clientes.enderecocliente')),
            ],
            options={
                'verbose_name': 'locacao',
                'verbose_name_plural': 'locacoes',
                'ordering': ['-data_inicio', 'codigo'],
            },
        ),
        migrations.CreateModel(
            name='ItemLocacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('valor_diaria', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('observacoes', models.CharField(blank=True, max_length=180)),
                ('ativo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_locacao', to='ativos.ativo')),
                ('locacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='locacoes.locacao')),
            ],
            options={
                'verbose_name': 'item de locacao',
                'verbose_name_plural': 'itens de locacao',
                'ordering': ['locacao__codigo', 'ativo__codigo'],
                'constraints': [models.UniqueConstraint(fields=('locacao', 'ativo'), name='item_locacao_ativo_unico')],
            },
        ),
    ]
