# Generated by Django 5.2 on 2026-07-28 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locacoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='locacao',
            name='data_pagamento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='locacao',
            name='status_pagamento',
            field=models.CharField(choices=[('aberto', 'Em aberto'), ('recebido', 'Recebido'), ('cancelado', 'Cancelado')], default='aberto', max_length=20),
        ),
    ]
