# Generated by Django 5.2 on 2026-07-10 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ativos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdemManutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('tipo', models.CharField(choices=[('preventiva', 'Preventiva'), ('corretiva', 'Corretiva')], default='corretiva', max_length=20)),
                ('status', models.CharField(choices=[('aberta', 'Aberta'), ('em_andamento', 'Em andamento'), ('finalizada', 'Finalizada'), ('cancelada', 'Cancelada')], default='aberta', max_length=20)),
                ('prioridade', models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Media'), ('alta', 'Alta')], default='media', max_length=20)),
                ('data_abertura', models.DateField(auto_now_add=True)),
                ('data_prevista', models.DateField(blank=True, null=True)),
                ('data_conclusao', models.DateField(blank=True, null=True)),
                ('responsavel', models.CharField(blank=True, max_length=120)),
                ('descricao', models.TextField()),
                ('solucao', models.TextField(blank=True)),
                ('custo_estimado', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('custo_real', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ativo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordens_manutencao', to='ativos.ativo')),
            ],
            options={
                'verbose_name': 'ordem de manutencao',
                'verbose_name_plural': 'ordens de manutencao',
                'ordering': ['status', '-data_abertura', 'codigo'],
            },
        ),
    ]
