# Generated by Django 5.2 on 2026-07-01 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaAtivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True)),
                ('ativa', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'categoria de ativo',
                'verbose_name_plural': 'categorias de ativos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Ativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('patrimonio', models.CharField(blank=True, max_length=50)),
                ('nome', models.CharField(max_length=160)),
                ('status', models.CharField(choices=[('disponivel', 'Disponivel'), ('locado', 'Locado'), ('manutencao', 'Manutencao'), ('inativo', 'Inativo')], default='disponivel', max_length=20)),
                ('localizacao_atual', models.CharField(blank=True, max_length=180)),
                ('permite_rastreamento', models.BooleanField(default=False)),
                ('horimetro_atual', models.DecimalField(decimal_places=1, default=0, max_digits=10)),
                ('proxima_manutencao_horas', models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ativos', to='ativos.categoriaativo')),
            ],
            options={
                'verbose_name': 'ativo',
                'verbose_name_plural': 'ativos',
                'ordering': ['codigo'],
            },
        ),
    ]
